### ISSUE TITLE
你好！请问有参考文献的链接吗？在谷歌学术上没有搜到，谢谢！

### ISSUE THREAD

**Issue by alexshaodong** [czh-98/CMS-LSTM#1]

**Comment by czh-98** [comment]
@article{chai2021cms,
  title={CMS-LSTM: Context-Embedding and Multi-Scale Spatiotemporal-Expression LSTM for Video Prediction},
  author={Chai, Zenghao and Yuan, Chun and Lin, Zhihui and Bai, Yunpeng},
  journal={arXiv preprint arXiv:2102.03586},
  year={2021}
}
